name: Publish Documentation

on:
  push:
    branches:
      - main
      - docs/**
    paths:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      brand:
        description: 'Brand to publish to'
        required: true
        type: string
      dry_run:
        description: 'Validate only without publishing'
        required: false
        type: boolean
        default: false

env:
  DOCS_API_URL: ${{ secrets.DOCS_API_URL || 'https://api.docs-publishing.example.com/v1' }}

jobs:
  validate:
    name: Validate Documentation
    runs-on: ubuntu-latest
    outputs:
      docs-changed: ${{ steps.changes.outputs.docs }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check for documentation changes
        id: changes
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "docs=true" >> $GITHUB_OUTPUT
          else
            git diff --name-only HEAD~1 HEAD | grep -q -E '\.(md|markdown|rst)$' && echo "docs=true" >> $GITHUB_OUTPUT || echo "docs=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Get changed files
        if: steps.changes.outputs.docs == 'true'
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            FILES=$(find docs -type f \( -name "*.md" -o -name "*.markdown" -o -name "*.rst" \))
          else
            FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.(md|markdown|rst)$')
          fi
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Validate documentation
        if: steps.changes.outputs.docs == 'true'
        run: |
          echo "Validating documentation files..."
          
          # Install validation tools
          pip install markdown-lint pyyaml
          
          # Validate each file
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "Validating $file"
              
              # Check frontmatter
              if head -1 "$file" | grep -q "^---$"; then
                echo "✓ Frontmatter found"
              else
                echo "⚠ Warning: No frontmatter in $file"
              fi
              
              # Check minimum content length
              WORD_COUNT=$(wc -w < "$file")
              if [ "$WORD_COUNT" -lt 100 ]; then
                echo "⚠ Warning: $file has less than 100 words ($WORD_COUNT words)"
              else
                echo "✓ Content length OK ($WORD_COUNT words)"
              fi
            fi
          done <<< "${{ steps.changed-files.outputs.files }}"
      
      - name: Spell check
        if: steps.changes.outputs.docs == 'true'
        continue-on-error: true
        run: |
          # Install spell checker
          sudo apt-get update && sudo apt-get install -y aspell
          
          echo "Running spell check..."
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              aspell list < "$file" | sort -u > /tmp/misspelled-$RANDOM.txt || true
            fi
          done <<< "${{ steps.changed-files.outputs.files }}"

  publish:
    name: Publish to Knowledge Base
    runs-on: ubuntu-latest
    needs: validate
    if: |
      needs.validate.outputs.docs-changed == 'true' && 
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up environment
        run: |
          echo "Setting up publishing environment..."
          pip install requests pyyaml
      
      - name: Determine brand
        id: brand
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            BRAND="${{ github.event.inputs.brand }}"
          else
            # Try to detect brand from repository or use default
            BRAND="${GITHUB_REPOSITORY_OWNER}"
          fi
          echo "brand=${BRAND}" >> $GITHUB_OUTPUT
          echo "Publishing to brand: ${BRAND}"
      
      - name: Publish documentation
        if: github.event.inputs.dry_run != 'true'
        env:
          DOCS_API_KEY: ${{ secrets.DOCS_API_KEY }}
          BRAND: ${{ steps.brand.outputs.brand }}
        run: |
          echo "Publishing documentation to $BRAND..."
          
          # Find all documentation files
          find docs -type f \( -name "*.md" -o -name "*.markdown" \) | while read -r file; do
            echo "Publishing $file"
            
            # Extract metadata from frontmatter
            TITLE=$(grep '^title:' "$file" | head -1 | sed 's/title: *"\(.*\)"/\1/' || basename "$file" .md)
            CATEGORY=$(grep '^category:' "$file" | head -1 | sed 's/category: *"\(.*\)"/\1/' || echo "general")
            
            # Create JSON payload
            PAYLOAD=$(cat <<EOF
          {
            "source": "$file",
            "brand": "$BRAND",
            "category": "$CATEGORY",
            "metadata": {
              "title": "$TITLE",
              "author": "${{ github.actor }}",
              "version": "${{ github.sha }}",
              "repository": "${{ github.repository }}"
            },
            "options": {
              "validate": true,
              "transform": true,
              "publish": true
            }
          }
          EOF
          )
            
            # Publish via API (mock for now)
            echo "Would publish: $PAYLOAD"
            # Uncomment when API is available:
            # curl -X POST "$DOCS_API_URL/publish" \
            #   -H "Authorization: Bearer $DOCS_API_KEY" \
            #   -H "Content-Type: application/json" \
            #   -d "$PAYLOAD"
          done
      
      - name: Dry run summary
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "## Dry Run Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✓ Validation completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "✓ No errors found" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** This was a dry run. Documentation was not published." >> $GITHUB_STEP_SUMMARY
      
      - name: Create deployment summary
        if: github.event.inputs.dry_run != 'true'
        run: |
          echo "## Documentation Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✓ Documentation published to **${{ steps.brand.outputs.brand }}**" >> $GITHUB_STEP_SUMMARY
          echo "✓ Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Published Files" >> $GITHUB_STEP_SUMMARY
          find docs -type f \( -name "*.md" -o -name "*.markdown" \) | while read -r file; do
            echo "- $file" >> $GITHUB_STEP_SUMMARY
          done

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [validate, publish]
    if: always() && needs.publish.result != 'skipped'
    
    steps:
      - name: Notify on success
        if: needs.publish.result == 'success'
        run: |
          echo "Documentation published successfully"
          # Add notification logic (Slack, email, etc.)
      
      - name: Notify on failure
        if: needs.publish.result == 'failure'
        run: |
          echo "Documentation publishing failed"
          # Add failure notification logic
